apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"jenkins-master","app.kubernetes.io/name":"jenkins-1"},"name":"jenkins-1-jenkins-agents-connector","namespace":"jenkins","ownerReferences":[{"apiVersion":"app.k8s.io/v1beta1","blockOwnerDeletion":true,"kind":"Application","name":"jenkins-1","uid":"29fe79f8-f635-4a99-89ea-5053b042f5d3"}]},"spec":{"ports":[{"name":"agents-connector","port":50000,"protocol":"TCP","targetPort":50000}],"selector":{"app.kubernetes.io/component":"jenkins-master","app.kubernetes.io/name":"jenkins-1"}}}
    creationTimestamp: "2021-10-21T23:20:14Z"
    labels:
      app.kubernetes.io/component: jenkins-master
      app.kubernetes.io/name: jenkins-1
    name: jenkins-1-jenkins-agents-connector
    namespace: jenkins
    ownerReferences:
    - apiVersion: app.k8s.io/v1beta1
      blockOwnerDeletion: true
      kind: Application
      name: jenkins-1
      uid: 29fe79f8-f635-4a99-89ea-5053b042f5d3
    resourceVersion: "1869"
    uid: 2b1b9cfe-3e3c-4b4f-962a-8cdf53cccd32
  spec:
    clusterIP: 10.116.2.95
    clusterIPs:
    - 10.116.2.95
    ports:
    - name: agents-connector
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app.kubernetes.io/component: jenkins-master
      app.kubernetes.io/name: jenkins-1
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
      cloud.google.com/neg-status: '{"network_endpoint_groups":{"8080":"k8s1-39dcdaf5-jenkins-jenkins-1-jenkins-ui-8080-7d27e221"},"zones":["asia-southeast1-a"]}'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"jenkins-master","app.kubernetes.io/name":"jenkins-1"},"name":"jenkins-1-jenkins-ui","namespace":"jenkins","ownerReferences":[{"apiVersion":"app.k8s.io/v1beta1","blockOwnerDeletion":true,"kind":"Application","name":"jenkins-1","uid":"29fe79f8-f635-4a99-89ea-5053b042f5d3"}]},"spec":{"ports":[{"name":"ui","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app.kubernetes.io/component":"jenkins-master","app.kubernetes.io/name":"jenkins-1"},"type":"NodePort"}}
    creationTimestamp: "2021-10-21T23:20:14Z"
    labels:
      app.kubernetes.io/component: jenkins-master
      app.kubernetes.io/name: jenkins-1
    name: jenkins-1-jenkins-ui
    namespace: jenkins
    ownerReferences:
    - apiVersion: app.k8s.io/v1beta1
      blockOwnerDeletion: true
      kind: Application
      name: jenkins-1
      uid: 29fe79f8-f635-4a99-89ea-5053b042f5d3
    resourceVersion: "1886"
    uid: cce65b44-d58f-4ca6-97f8-245d2e448e38
  spec:
    clusterIP: 10.116.5.242
    clusterIPs:
    - 10.116.5.242
    externalTrafficPolicy: Cluster
    ports:
    - name: ui
      nodePort: 30151
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/component: jenkins-master
      app.kubernetes.io/name: jenkins-1
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
